version = 0.1

[default]
[default.global.parameters]
stack_name = "monitor-recording-leakage"
parameter_overrides = [
    "RegionPrefix=afs1",
    "Stage=dev",
    "LambdaRoleArn=arn:aws:iam::687244881512:role/lambda-admin-access",
    "ConnectInstanceId=bd7c61d1-6722-4b4f-8c9c-6253e5a85c32",
    "ConnectInstanceAlias=capetown",
    "ConnectLogGroup=/aws/connect/capetown",
    "CallRecordingsBucket=amazon-connect-d544b3c5c365",
    "StepFunctionRoleArn=arn:aws:iam::687244881512:role/step-function-admin"
]

[default.build.parameters]
cached = true
parallel = true
template_file = 'template.yaml'
region = 'af-south-1'

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_bucket = "sash-sam"
s3_prefix = "monitor-recording-leakage"
template_file = 'cf-template.yaml'
region = "af-south-1"
tags = [
    "Project=monitor-recording-leakage",
    "CreatedBy=sash"
]

[default.package.parameters]
s3_bucket = "sash-sam"
s3_prefix = "monitor-recording-leakage"
output_template_file = "cf-template.yaml"
config_file = "samconfig.toml"

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
